before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: filt-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  ldflags:
    - -s -w -X github.com/k1LoW/filt.version={{.Version}} -X github.com/k1LoW/filt.commit={{.FullCommit}} -X github.com/k1LoW/filt.date={{.Date}} -X github.com/k1LoW/filt/version.Version={{.Version}}
-
  id: filt-darwin
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  ldflags:
    - -s -w -X github.com/k1LoW/filt.version={{.Version}} -X github.com/k1LoW/filt.commit={{.FullCommit}} -X github.com/k1LoW/filt.date={{.Date}} -X github.com/k1LoW/filt/version.Version={{.Version}}
archives:
-
  id: filt-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
brews:
-
  name: filt
  github:
    owner: k1LoW
    name: homebrew-tap
  commit_author:
    name: k1LoW
    email: k1lowxb@gmail.com
  homepage: https://github.com/k1LoW/filt
  description: 'filt is a interactive/realtime stream filter.'
  install: |
    system './filt', 'completion', 'bash', '--out', 'filt.bash'
    system './filt', 'completion', 'zsh', '--out', 'filt.zsh'
    bin.install 'filt'
    bash_completion.install 'filt.bash' => 'filt'
    zsh_completion.install 'filt.zsh' => '_filt'
nfpms:
  -
    id: filt-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - filt-linux
    homepage: https://github.com/k1LoW/filt
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: filt is a interactive/realtime stream filter.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
