before:
  hooks:
    - go mod download
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/k1LoW/filt.version={{.Version}} -X github.com/k1LoW/filt.commit={{.FullCommit}} -X github.com/k1LoW/filt.date={{.Date}} -X github.com/k1LoW/filt/version.Version={{.Version}}
archives:
-
  id: filt-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
brews:
-
  name: filt
  github:
    owner: k1LoW
    name: homebrew-tap
  commit_author:
    name: k1LoW
    email: k1lowxb@gmail.com
  homepage: https://github.com/k1LoW/filt
  description: 'filt is a interactive/realtime stream filter.'
  install: bin.install 'filt'
