name: Test
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Install codecov
        run: sudo pip install codecov

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Test
        run: env PATH=`go env GOPATH`/bin:$PATH make ci
        env:
          GOPROXY: "https://proxy.golang.org"

      - name: Run codecov
        run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
